-- SEQUENCE: public.demis_record_id_seq

-- DROP SEQUENCE public.demis_record_id_seq;

CREATE
SEQUENCE public.demis_record_id_seq
    INCREMENT 1
    START 6
    MINVALUE 0
    MAXVALUE 9223372036854775807
    CACHE 1;

    -- ALTER SEQUENCE public.demis_record_id_seq
    --   OWNER TO demis;


    -- Table: public.demis_table

    -- DROP TABLE public.demis_table;

CREATE TABLE public.demis_table
(
    technical_id  character varying COLLATE pg_catalog."default",
    demis_id      character varying COLLATE pg_catalog."default",
    family_name   character varying[] COLLATE pg_catalog."default",
    first_name    character varying[] COLLATE pg_catalog."default",
    disease_code  character varying COLLATE pg_catalog."default",
    date_of_birth character varying COLLATE pg_catalog."default",
    record_id     integer NOT NULL DEFAULT nextval('demis_record_id_seq'::regclass),
    creation_time timestamp without time zone,
    pho_code      character varying COLLATE pg_catalog."default"
)
WITH ( OIDS = FALSE) TABLESPACE pg_default;

-- ALTER TABLE public.demis_table
--   OWNER to demis;

COMMENT ON COLUMN public.demis_table.demis_id
    IS 'Id der Meldung';

COMMENT ON COLUMN public.demis_table.pho_code
    IS 'Code des Gesundheitsamtes';

COMMENT ON COLUMN public.demis_table.family_name
    IS 'Pseudonymisierte Elemente des Familiennamen nach Normalisierung, Base64-kodiert';

COMMENT ON COLUMN public.demis_table.first_name
    IS 'Pseudonymisierte Elemente des Vornamens nach Normalisierung, Base64-kodiert';

COMMENT ON COLUMN public.demis_table.disease_code
    IS 'Pseudonymisierter Meldetatbestand, Base64-kodiert';

COMMENT ON COLUMN public.demis_table.date_of_birth
    IS 'Pseudonymisiertes Geburtsdatum, Base64-kodiert';

COMMENT ON COLUMN public.demis_table.creation_time
    IS 'Zeitstempel der Erzeugung (ohne Timezone)';

    -- Index: disease_dob

    -- DROP INDEX public.disease_dob;

CREATE INDEX disease_dob
    ON public.demis_table USING btree
    (disease_code COLLATE pg_catalog."default" ASC NULLS LAST, date_of_birth COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

INSERT INTO public.demis_table(technical_id,demis_id,pho_code,family_name,first_name,disease_code,date_of_birth, creation_time)
VALUES
    ('0','demisId:00','1.01.0.51.','{AAEAJQBAAwAAAACACwAAEIYiRAoAACIAAAAggAAAIABCECAAIAAAAALAIggACAIAQABAAAIiAgAAIAIQBCCAAAEgmSALIAAgEAAAAAAAYoAABAAEQACAECIAgAEgDAYANAESAAQAAAICASAAAAQAQABgAggABIiiEBAQIAIAACE=,AQIACASCAAAAAISACIAEiBABAABwAACAEAIAAMQAIAABAABIAQBAEIABAARACIQAAAACAYAAAAAAwAAAAgAABIAAAgAggAAAAASCMEADIBIAgIAAABCgwQAgCAACgAIAAMTAAAAgCAAICBAQATCBASAACAAAQAACEQCEAAAAAIA=,gCiAyAAAgAEAAAARAAAAsABABDCAAAAAihiAQACAggBQAMAABAAACCEAAACKAAAEaACAAAAAkACREagAEEAQAAAhAAAAAwAAIAAAAAzAgBAAIIAAAgCBACKiBAAACAIAAAAQAAACxAADBIAEACCpAQhAAAoQhAEEZEZBjFACihA=}','{AAAAGAAEAAAAKAAAEBAAoCBUAQAAAAJBACAggAkAAQEAgCAACIClAAAAEIgAEAAAAAACAlAACABAAAgAJQAYQAEAgAAIAAIEGAIgIAADEAgAKAAAIGAAAQAAEACAAQAAgAEAAgAA0IEACIABAAKCMAAAAAAAhEACAhgAgA4AAQg=,gAEAQBAoAAEBAgwAIAAAEAACQAAAQQAwAAQBAFgAASAADhAgAAAAAAJAEAggAAEAABAAAgAAgIAEiECQIAEABAAASAABIAQAAIAAACAAIACAABAIAgQMEEAAAAUgQAQAAAAAAAAIAAAAAAICZACoQIAAAAAAJIAAEgAgAAACAAA=,gIAgQQAqACEAAAgEAAQAAoCwAAAQAAFhAAASIVgAASAARgAIAABAAgIACEAhIAIAgAAgAgCAGIIUgAAxIAAAghQAABAANUAAiIAkAAAAIASDMBBIggwCAAQYBABAAAAEAIAgAAZIAABAAAKCQQDKBAgABBiAAgAAgAkAAACATQA=}','covid19','BIAhBxiSgEpAkmASYTo4IAOEBngYIJmCEEQGAgETAIMDB4UiroEgEcj/f2IRICkKkpNABhIGrY4QYBDpIgqAOw==', current_date at time zone 'Europe/Berlin'),
    ('0','demisId:01','1.01.0.51.','{AAEAJQBAAwAAAACACwAAEIYiRAoAACIAAAAggAAAIABCECAAIAAAAALAIggACAIAQABAAAIiAgAAIAIQBCCAAAEgmSALIAAgEAAAAAAAYoAABAAEQACAECIAgAEgDAYANAESAAQAAAICASAAAAQAQABgAggABIiiEBAQIAIAACE=,AQIACASCAAAAAISACIAEiBABAABwAACAEAIAAMQAIAABAABIAQBAEIABAARACIQAAAACAYAAAAAAwAAAAgAABIAAAgAggAAAAASCMEADIBIAgIAAABCgwQAgCAACgAIAAMTAAAAgCAAICBAQATCBASAACAAAQAACEQCEAAAAAIA=,gCiASQAAgCIAACARBAAAsIAAhDAAAAgAihiAQACAggBQAIIABAAACCEAAACKgAAESACAAAAAkACRMagAEEIAAAAhAAAAAwAAoAAAAATAgAACIIAAYgCBACKqAAAAAAMACAAwgAACxAQBBICAAiCpIRhAAAoQhgAEZERBjFACihA=}','{AAAAGAAEAAAAKAAAEBAAoCBUAQAAAAJBACAggAkAAQEAgCAACIClAAAAEIgAEAAAAAACAlAACABAAAgAJQAYQAEAgAAIAAIEGAIgIAADEAgAKAAAIGAAAQAAEACAAQAAgAEAAgAA0IEACIABAAKCMAAAAAAAhEACAhgAgA4AAQg=,gIAgQQAqACEAAAgEAAQAAoCwAAAQAAFhAAASIVgAASAARgAIAABAAgIACEAhIAIAgAAgAgCAGIIUgAAxIAAAghQAABAANUAAiIAkAAAAIASDMBBIggwCAAQYBABAAAAEAIAgAAZIAABAAAKCQQDKBAgABBiAAgAAgAkAAACATQA=,gAAAQAAoAgEAAAgIAAAAECACQAAAAQAwAAABABgAASAABgAAAAAAAAJAAAgAABAAAAAAQgAAgIAEiQCQIAAEAAAACBABIAgAQIQAAAIAIQGAgBAIQgAEIEAAEAUgSAQABAAAAgAIAQCAAALCQACIAAACAAAAJIgAEgAgIAACAAA=}','covid19','BIAhBxiSgEpAkmASYTo4IAOEBngYIJmCEEQGAgETAIMDB4UiroEgEcj/f2IRICkKkpNABhIGrY4QYBDpIgqAOw==', current_date at time zone 'Europe/Berlin' - make_interval(days => 88)),
    ('0','demisId:02','1.01.0.51.','{AQIACASCAAAAAISACIAEiBABAABwAACAEAIAAMQAIAABAABIAQBAEIABAARACIQAAAACAYAAAAAAwAAAAgAABIAAAgAggAAAAASCMEADIBIAgIAAABCgwQAgCAACgAIAAMTAAAAgCAAICBAQATCBASAACAAAQAACEQCEAAAAAIA=,gCiASQAAgCIAACARBAAAsIAAhDAAAAgAihiAQACAggBQAIIABAAACCEAAACKgAAESACAAAAAkACRMagAEEIAAAAhAAAAAwAAoAAAAATAgAACIIAAYgCBACKqAAAAAAMACAAwgAACxAQBBICAAiCpIRhAAAoQhgAEZERBjFACihA=,AIEBBQAAAQgAAAAACQAAEKYiRAoAAAAAgAAAgAAAAABAFAQAoAAAAALAKAgACAIAwIBAAAACCgAAAACQAACAAAEQmSAJIACgAAAAAAAIQIAABgIEAACAEAAIAAEgDIYAVEAQAAQAAAAAAaAAAAAAQAhoCAAABIiCEAAQAAgAAAE=}','{AAAAGAAEAAAAKAAAEBAAoCBUAQAAAAJBACAggAkAAQEAgCAACIClAAAAEIgAEAAAAAACAlAACABAAAgAJQAYQAEAgAAIAAIEGAIgIAADEAgAKAAAIGAAAQAAEACAAQAAgAEAAgAA0IEACIABAAKCMAAAAAAAhEACAhgAgA4AAQg=,gIAgQQAqACEAAAgEAAQAAoCwAAAQAAFhAAASIVgAASAARgAIAABAAgIACEAhIAIAgAAgAgCAGIIUgAAxIAAAghQAABAANUAAiIAkAAAAIASDMBBIggwCAAQYBABAAAAEAIAgAAZIAABAAAKCQQDKBAgABBiAAgAAgAkAAACATQA=,wAAAAAIgAgAAAAgIBAAAkCACSBAAAQAwAACBABgAAAAAAgAAAAIAAEJCAAgIAJAAACAAQggAgIoAiQCAIAAFiAAgCBABJAAASIAAAAAAIwAAAAAIAAAkAEAAEAUgQAYCAEAAAIAIAAAAAAKAABiAAAQCAAkA5IgBEgAgJAACAQA=}','covid19','BIAhBxiSgEpAkmASYTo4IAOEBngYIJmCEEQGAgETAIMDB4UiroEgEcj/f2IRICkKkpNABhIGrY4QYBDpIgqAOw==', current_date at time zone 'Europe/Berlin'),
    ('0','demisId:03','1.01.0.51.','{AAEAJQBAAwAAAACACwAAEIYiRAoAACIAAAAggAAAIABCECAAIAAAAALAIggACAIAQABAAAIiAgAAIAIQBCCAAAEgmSALIAAgEAAAAAAAYoAABAAEQACAECIAgAEgDAYANAESAAQAAAICASAAAAQAQABgAggABIiiEBAQIAIAACE=,gCiAyAAAgAEAAAARAAAAsABABDCAAAAAihiAQACAggBQAMAABAAACCEAAACKAAAEaACAAAAAkACREagAEEAQAAAhAAAAAwAAIAAAAAzAgBAAIIAAAgCBACKiBAAACAIAAAAQAAACxAADBIAEACCpAQhAAAoQhAEEZEZBjFACihA=}','{AAAAGAAEAAAAKAAAEBAAoCBUAQAAAAJBACAggAkAAQEAgCAACIClAAAAEIgAEAAAAAACAlAACABAAAgAJQAYQAEAgAAIAAIEGAIgIAADEAgAKAAAIGAAAQAAEACAAQAAgAEAAgAA0IEACIABAAKCMAAAAAAAhEACAhgAgA4AAQg=,wAAAAAIgAgAAAAgIBAAAkCACSBAAAQAwAACBABgAAAAAAgAAAAIAAEJCAAgIAJAAACAAQggAgIoAiQCAIAAFiAAgCBABJAAASIAAAAAAIwAAAAAIAAAkAEAAEAUgQAYCAEAAAIAIAAAAAAKAABiAAAQCAAkA5IgBEgAgJAACAQA=,gIAAQQCqACEAEAgAAAAAAIAQAAAQAAFiQABSBUhAASAERkAIAABAAAgACAAhIAIAgAAgAgCAEIIEoAAwIAQAApQAABAEEEAACIQAQAAANASCIBJIAgQCAAQIBABAAABEAAAgCAQIAAAAAAKCQQSIRAgBBADgAgAEAAkAAACACQA=}','covid19','BIAhBxiSgEpAkmASYTo4IAOEBngYIJmCEEQGAgETAIMDB4UiroEgEcj/f2IRICkKkpNABhIGrY4QYBDpIgqAOw==', current_date at time zone 'Europe/Berlin'),
    ('1','demisId:10','1.01.0.51.','{ABAARAAAAKQBAAAMAAAQkAAqSAAAAAAAEAAACIgAAICAQAAAAAIIGAJIAAiACAACAIQAgAAEEACABAAADAQMAAAEqABBNAAIgAQABCAEAAAAQACIAAAIAAgABAEggAQACwAAAoAAAAAILAIAAAAAAQIAgIRAhIAEEAAIBQCIAQQ=}','{CQBAAhAAggKAAAAAAAwQgAAAIIAgAABAOAAAgAABAAAACA4CAAgAgYAAAgAAAACIACUAAAGAAAAAAAkFCBAAEAACUAAAAAAAAVCAEAAAAAAgCRAQBAAAgAQACAAAEQgQAgABAIBAAAAAgCAAgQAAIAgAAAAAIgEgAIgAAAAAiCA=,QQAQgAAgAAAAAIAAgAIABAKBQAQCABAAgAigKgAAANAAAQAACCAAAAQBAAAAIAAAAAAMAAACgAKAKDCYDAICgAogAQBAqAoIAgwAAAAADQAQACAACAgAAAAAAAAICAAAAAAACLFAIBAAACCAAAAAAOoSAAAAgIQAQUAAEIAFAAE=}','covid19','EAxBLioiRq2qgsChoMoIIDEoIgAATIIAAgCkMuG7IaIQBAAAKxEAA4D//yhoaiIJEJC6wgQAIjA9wQLKSmYMMA==', current_date at time zone 'Europe/Berlin'),
    ('1','demisId:11','1.01.0.51.','{ABAARAAAAKQBAAAMAAAQkAAqSAAAAAAAEAAACIgAAICAQAAAAAIIGAJIAAiACAACAIQAgAAEEACABAAADAQMAAAEqABBNAAIgAQABCAEAAAAQACIAAAIAAgABAEggAQACwAAAoAAAAAILAIAAAAAAQIAgIRAhIAEEAAIBQCIAQQ=}','{QACwgAAAAAAAAICAAAIABAKBQQcAAAAAgAiwKgIAAJAAQAgIACIAAAABAAAAAAIABEBIAAAIAAKAKDCYDAIKgAggQwIAqAoIAgABAAAALAAABBAQCAgAIBAAAAAIAAAAIICASJFAIBAAICABAAAAAOoCBAQAgIQAAdAAEIAFAAE=}','covid19','EAxBLioiRq2qgsChoMoIIDEoIgAATIIAAgCkMuG7IaIQBAAAKxEAA4D//yhoaiIJEJC6wgQAIjA9wQLKSmYMMA==', current_date at time zone 'Europe/Berlin'),
    ('2','demisId:20','1.01.0.51.','{EAEACBAACQgAAAQCAIAIAEAAARAAAAAAADBQAEAgAAgAAAIAAAEBAQIECQAAAQAFAQAQFYAIKQAAAQAAAQAAERgAAQAAAwAAABAgABIQAQAACgAhAEAAAAEAAAAJAYAgAAADEAAcEAgAAAAAAAASAgAAAAIAAABADCBAACEAABA=}','{AAAAAAIYAAAAgECACAAAAAQICCAIAAAAAUCIAIgEKAAISAgIAAQACAAAAIAAAACAAAAQAAgAAACACgAIiACBwACACCAACAAAAAAIQACBAAgAAAAAQAAIAAEAABqACAgJAAgACACAgAAABAgAAAABCAAIAAAAAACIAAAgAAAAAgI=,AAAkSdIsAAAAAACACAAAAAQAAAAIAAAAAEAAAIAAAAAIiAAAAAAACACAAwAAAAAAAAAQAAAAAAAACAAIAAAAAACACCAAAAACAAAIQAAAAAwAAAAAcAAICAAAAACAAAgAAAAAAACAgAAAAAgACAABCAAIAAAQAACAAAAAACAAAB4=}','covid19','CKCDAOCQhkCA6IFBoAHAAlwAIQiAABQABCABapAgFAzAQAEIQMIBwACAhYEAxCAgIgQhFAoOwABCBQsFAgDAFA==', current_date at time zone 'Europe/Berlin' - make_interval(days => 88)),
    ('2','demisId:21','1.01.0.51.','{AAEgCBAACQAAAAYBAAgIAEAAIRAAAAAAAgBAIEAgCAgAAIAAAAEBAQAECQAAIwCFAUAABYAIAQAIAQAAAQAAERgIAQIAAwAAABAAAAKAAQAACIABAEAAADEAAAAJAQAAAAABEAwEAAoAAACAAAAQAgAAAAAAgADgLABAAAEAAAQ=}','{AAIEAAAAAAAIAEKAAAAAAAAAAAAIAQAABAAAAIAAAQAAIAIKAAJAIAAAAQgAAQEAAQQAAQAAAQSACYAAIQAIAQCAAcAQAQAAAAAIBAAAIoAQAAAAEAAAYAAaAAAAAAgAAAAAAAgAggAAAAAAAAAADIAAYAAAAACAAAECAAAgAAg=}','covid19','CKCDAOCQhkCA6IFBoAHAAlwAIQiAABQABCABapAgFAzAQAEIQMIBwACAhYEAxCAgIgQhFAoOwABCBQsFAgDAFA==', current_date at time zone 'Europe/Berlin'),
    ('3','demisId:30','1.01.0.51.','{CIAAhAEABggCAABACQAAEAACwBIIAAAAChAChEIAAAAAAQABIAiAAAJAUChCCAIAAAgQAAAgAoAACAQAAECCAAIACAABIAEggAAMgABAQIACAQIAABAAEAAAIAmgBIQABAADAgIBAAAAAQAAQIAADABAABASBIJAEAAQAAQAAAA=}','{kwAAAAACAYAAAACAAyBAGEEAIAAQAgBAAAAAADIAgAEQAUqgBAAAAAAAACQAASQEAC0ALIAAgAIAABoAADgAECgQMIAIAAoiABAIAAAhAUCAKAUAAgIACiAAqAAIhBEAQQoAAAIAAEAAggABAAIEgUQAAAACAYAAgAAAECAAMJA=,QIIQoCQGAAgAAJAACCIBAkCBAIgQIABBiAAKAYEFAIAIAFAQAABgikAACAEAIAIAoEAIUBACAAKACCAACwAKoAwgABAAAFAIhAAgEgIACIAACAAAABiTAACIAAAIgASAAAAISAAAQAAAACQAASAEBAAgAAAggARQIUSCGIAEASE=}','covid19','ROHBgiAxQQMxBEUMIUCdkIKkASVAEjGABMAhxsaTI0ICMgcCiwIjMs7//wIpABcgAAARBVDIgcASYiEIQgqJEQ==', current_date at time zone 'Europe/Berlin' - make_interval(days => 120)),
    ('3','demisId:31','1.01.0.51.','{CIAAgAkAAgAGAABAiAAACAAAoBAIACIAAqAKBEICEAAAIQABAAiAAAAAQBAiAAIAAggQkAAgAKEACBQAAAKDAAJAAAAAAAEAgIAMgABAQAACAAIIiBAAgAAAIAiCBIAACAACAgIBAAIAIAAAQIAADAAAAhASBCJAQAgABAQAAAA=}','{QIIQoCQGAAgAAJAACCIBAkCBAIgQIABBiAAKAYEFAIAIAFAQAABgikAACAEAIAIAoEAIUBACAAKACCAACwAKoAwgABAAAFAIhAAgEgIACIAACAAAABiTAACIAAAIgASAAAAISAAAQAAAACQAASAEBAAgAAAggARQIUSCGIAEASE=}','covid19','ROHBgiAxQQMxBEUMIUCdkIKkASVAEjGABMAhxsaTI0ICMgcCiwIjMs7//wIpABcgAAARBVDIgcASYiEIQgqJEQ==', current_date at time zone 'Europe/Berlin' - make_interval(days => 90) );
